# Generated by Django 5.1 on 2024-09-17 06:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_experiencemodel_alter_contactmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencemodel',
            name='logo',
            field=models.FileField(upload_to='experience/logo/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'jpeg', 'jpg', 'webp', 'png'])], verbose_name='Лого'),
        ),
    ]
