# Generated by Django 4.2.7 on 2023-11-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_projectsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsmodel',
            name='link',
            field=models.URLField(default=0),
        ),
    ]
