# Generated by Django 5.1 on 2024-09-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_experiencemodel_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencemodel',
            name='created_at',
        ),
        migrations.AddField(
            model_name='experiencemodel',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='experiencemodel',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
    ]
