# Generated by Django 4.2.7 on 2023-11-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_projectsmodel_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsmodel',
            name='link',
            field=models.URLField(),
        ),
    ]
