# Generated by Django 4.2.7 on 2023-11-19 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_projectsmodel_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsmodel',
            name='post_text',
        ),
    ]
